name: Validate files

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /public/events.schema.json
          INPUT_JSONS: /public/events.json
      - name: HTML5Validator
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: public/
          blacklist: invalid
  
    